name: latihan_responsi_pam
description: Latihan Responsi Praktikum PAM - News, Blog, Report App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  url_launcher: ^6.2.1
  path: ^1.9.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
